Repository PowerShell/vscode-powershell, pull requests merged in 2019-03, with the labels that each got.

#1781 fix initial launch config casing
  package.json
Labels: Backport-Legacy, Triage

#1775 Support -CustomPipeName
  package.json
  src/features/DebugSession.ts
Labels: Backport-Legacy, Triage

#1782 Add Debug Runspace command
  package.json
  src/features/DebugSession.ts
  src/main.ts
Labels: Triage

#1816 Workaround PSSA #1187 by defaulting to NoIndentation
  package.json
  src/settings.ts
Labels: Backport-Legacy
