Repository PowerShell/vscode-powershell, pull requests merged in 2020-07, with the labels that each got.

#2788 Fix quoting of banner for global tool
  src/session.ts
Labels: Area-Startup, Issue-Bug

#2796 Add setting to change the cwd of the Powershell Integrated Console
  package.json
  src/process.ts
  src/settings.ts
Labels: Area-Integrated Console, Issue-Enhancement

#2830 When migrating old whitespaceAroundPipe setting to AddWhitespaceAroundPipe, remove old setting now
  package.json
  src/session.ts
Labels: Area-Code Formatting, Area-Configuration, Issue-Meta
