Repository PowerShell/vscode-powershell, pull requests merged in 2021-08, with the labels that each got.

#3493 Update extension icon (and use a special preview icon)
  media/PowerShell_Icon.png
  media/PowerShell_Preview_Icon.png
  media/PowerShell_icon.png
  package.json
  tools/ReleaseTools.psm1
  tools/postReleaseScripts/updateAzureDataStudio.ps1
Labels: Area-UI, Issue-Enhancement

#3494 Release `v2021.8.0-preview`
  .vsts-ci/templates/publish-markets.yml
  CHANGELOG.md
  docs/development.md
  package.json
  tools/ReleaseTools.psm1
  vscode-powershell.build.ps1
Labels: Ignore

#3503 Release `v2021.8.0`
  .markdownlint.json
  CHANGELOG.md
  package.json
Labels: Ignore

#3502 (#3499) Remove msjsdiag.debugger-for-chrome suggestion
  .vscode/extensions.json
Labels: Issue-Bug

#3506 Update test runner
  package-lock.json
  package.json
  test/core/platform.test.ts
  test/core/settings.test.ts
  test/fixtures/.gitattributes
  test/index.ts
  test/runTests.ts
  test/test_utils.ts
Labels: Issue-Enhancement, Area-Test

#3512 Release `v2021.8.1-preview`
  CHANGELOG.md
  package.json
  tools/ReleaseTools.psm1
Labels: Ignore

#3514 Fix extension version in bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Ignore

#3520 Release `v2021.8.2-preview`
  CHANGELOG.md
  package.json
  tools/ReleaseTools.psm1
Labels: Ignore

#3523 Release `v2021.8.2`
  CHANGELOG.md
  package.json
Labels: Ignore

#3536 Release `v2021.8.3-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
