Repository PowerShell/vscode-powershell, pull requests merged in 2021-05, with the labels that each got.

#3329 Fix duplicated command registrations
  package.json
  src/features/ExtensionCommands.ts
Labels: Area-UI, Issue-Bug

#3333 Update troubleshooting and contacts
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  docs/troubleshooting.md
Labels: Ignore

#3335 Delete deprecated `updatePsesVersions.ps1`
  tools/postReleaseScripts/updatePsesVersions.ps1
Labels: Ignore

#3340 Update Description to reflect that PowerShell is for more than scripting
  package.json
  tools/ReleaseTools.psm1
  tools/postReleaseScripts/updateAzureDataStudio.ps1
  vscode-powershell.build.ps1
Labels: Area-Documentation, Issue-Enhancement

#3356 Use PowerShell terminal icon (when available)
  src/session.ts
Labels: Area-UI, Issue-Enhancement

#3179 Update @types/vscode and `StatusBarItem` implementation
  package-lock.json
  package.json
  src/controls/animatedStatusBar.ts
Labels: dependencies

#3359 Exclude `-` and `$` from PowerShell `wordSeparators`
  package.json
Labels: Area-Symbols & References, Issue-Enhancement

#3358 Fix bugs in `ReleaseTools`
  tools/ReleaseTools.psm1
Labels: Area-Build & Release, Ignore

#3361 Fix another bug in `ReleaseTools`
  tools/ReleaseTools.psm1
  vscode-powershell.build.ps1
Labels: Area-Build & Release, Ignore

#3362 Release `v2021.5.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3357 Don't prompt to save untitled PowerShell files when debugging
  package.json
Labels: Area-Configuration, Area-Debugging, Issue-Bug, Issue-Enhancement

#3372 Note that ISE theme is included in this extension
  README.md
  docs/troubleshooting.md
Labels: Area-Documentation, Area-UI, Issue-Enhancement

#3377 Disable semantic highlighting by default
  docs/troubleshooting.md
  package.json
Labels: Area-Semantic Highlighting, Issue-Discussion
