Repository PowerShell/vscode-powershell, pull requests merged in 2021-03, with the labels that each got.

#3212 Remove the rest of the experimental Notebook API
  .gitignore
  .vscode/launch.json
  package-lock.json
  package.json
  resources/dark/book.svg
  resources/dark/file-code.svg
  resources/light/book.svg
  resources/light/file-code.svg
  test/features/testNotebookFiles/blockCommentsWithTextOnSameLine.ps1
  test/features/testNotebookFiles/onlyCode.ps1
  test/features/testNotebookFiles/onlyMarkdown.ps1
  test/features/testNotebookFiles/simple.Notebook.ps1
  test/features/testNotebookFiles/simpleBlockComments.ps1
  test/features/testNotebookFiles/simpleLineComments.ps1
  test/features/testNotebookFiles/simpleMixedComments.ps1
Labels: Issue-Bug

#3214 Update examples-module to use Pester 5
  examples/Tests/PathProcessing.Tests.ps1
  examples/Tests/SampleModule.Tests.ps1
Labels: Area-Documentation, Issue-Bug

#3222 Fix hardcoded extension name string
  test/features/ExternalApi.test.ts
  test/runTests.ts
Labels: Area-Test, Issue-Bug

#3237 Use title case and shorter notification text
  src/features/UpdatePowerShell.ts
Labels: Area-UI, Issue-Enhancement
