Repository PowerShell/vscode-powershell, pull requests merged in 2021-09, with the labels that each got.

#3544 Document the trace server setting is valid (despite Code's warning)
  docs/troubleshooting.md
Labels: Issue-Enhancement, Area-Documentation

#3542 Allow PowerShell session to start and stop the debugger interface
  .vscode/launch.json
  .vscode/tasks.json
  src/features/DebugSession.ts
Labels: Issue-Discussion, Area-Debugging

#3548 Release `v2021.9.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3549 Fix `ReleaseTools` issue matcher regex
  tools/ReleaseTools.psm1
Labels: Ignore

#3551 Revert "Bump @types/node-fetch from 2.5.12 to 3.0.3 (#3545)"
  package-lock.json
  package.json
Labels: Ignore

#3557 Release `v2021.9.0`
  CHANGELOG.md
  package.json
Labels: Ignore

#3559 Spelling fix for README
  examples/README.md
Labels: Ignore

#3555 Bundle the extension
  .vscode/launch.json
  .vscodeignore
  extension-dev.code-workspace
  package-lock.json
  package.json
  src/features/Examples.ts
  src/features/PesterTests.ts
  src/logging.ts
  src/main.ts
  src/platform.ts
  src/settings.ts
  test/features/CustomViews.test.ts
  tsconfig.json
  vscode-powershell.build.ps1
Labels: Issue-Enhancement, Area-Build & Release

#3564 Remove accidentally enabled commands
  package.json
  src/features/ExternalApi.ts
Labels: Issue-Bug, Area-UI

#3569 Release `v2021.9.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3570 Fix path regressions and cover with tests
  .vsts-ci/templates/ci-general.yml
  src/features/Examples.ts
  src/features/PesterTests.ts
  src/settings.ts
  src/utils.ts
  test/core/paths.test.ts
  test/features/CustomViews.test.ts
  test/features/ExternalApi.test.ts
  test/features/ISECompatibility.test.ts
  test/features/RunCode.test.ts
  test/runTests.ts
  test/utils.ts
Labels: Issue-Bug, Area-Test

#3591 Bump dependencies and lockfile
  package-lock.json
Labels: dependencies

#3593 Remove `mocha-junit-reporter` package by relying on Mocha's xUnit module
  package-lock.json
  package.json
  test/index.ts
Labels: dependencies

#3595 Release `v2021.9.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
