Repository PowerShell/vscode-powershell, pull requests merged in 2022-04, with the labels that each got.

#3911 Add `sendKeyPress` notification used to "cancel" `Console.ReadKey`
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-PSReadLine

#3917 Release `v2022.4.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3919 Improve Settings Editor experience in a few places
  package.json
  src/platform.ts
  src/session.ts
  src/settings.ts
  test/core/settings.test.ts
Labels: Issue-Enhancement, Area-UI

#3924 Release `v2022.4.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3930 Release `v2022.4.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3933 Update GitHub code owners
  .github/CODEOWNERS
  .poshchan/settings.json
Labels: Ignore

#3936 Add `package.json` as developer file to code owners
  .github/CODEOWNERS
Labels: Ignore

#3939 Send `p` instead of `\0` for `sendKeyPress`
  src/process.ts
Labels: Issue-Bug, Area-PSReadLine

#3941 Release `v2022.4.3-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
