Repository PowerShell/vscode-powershell, pull requests merged in 2022-03, with the labels that each got.

#3853 Update `engines.vscode` and run `npm update`
  package-lock.json
  package.json
  src/controls/animatedStatusBar.ts
Labels: Ignore

#3854 Use new `isTransient` API to prevent duplicate integrated consoles
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-Integrated Console

#3865 Replace custom graphics with updated Codicons
  media/pwsh.svg
  media/resources/dark/pencil.svg
  media/resources/dark/play.svg
  media/resources/dark/question.svg
  media/resources/dark/run.svg
  media/resources/dark/sync.svg
  media/resources/light/pencil.svg
  media/resources/light/play.svg
  media/resources/light/question.svg
  media/resources/light/run.svg
  media/resources/light/sync.svg
  package.json
Labels: Issue-Enhancement, Area-UI

#3839 Modernize built-in snippets
  docs/community_snippets.md
  snippets/PowerShell.json
Labels: Issue-Enhancement, Area-Snippets

#3866 Fix title of PowerShell Command Explorer pane
  package.json
  src/features/ISECompatibility.ts
Labels: Issue-Enhancement, Area-UI

#3859 Deprecate `promptToUpdatePackageManagement`
  package.json
  src/settings.ts
Labels: Issue-Enhancement, Area-Configuration

#3869 Use Code's new Language Status API
  src/process.ts
  src/session.ts
Labels: Issue-Enhancement, Area-UI

#3870 Release `v2022.3.0-preview`
  CHANGELOG.md
  package.json
  tools/ReleaseTools.psm1
Labels: Ignore

#3877 Add PowerShell version to language status item
  src/session.ts
Labels: Issue-Bug, Area-UI

#3879 Update troubleshooting guide etc.
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
  SECURITY.md
  docs/troubleshooting.md
Labels: Issue-Bug, Area-Documentation

#3883 Add several more commands to activation events
  package.json
Labels: Issue-Bug, Area-UI

#3890 Release `v2022.3.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3897 Add PowerShell icon to Integrated Console
  src/process.ts
Labels: Issue-Enhancement, Area-UI
