Repository PowerShell/vscode-powershell, pull requests merged in 2022-05, with the labels that each got.

#3946 Release `v2022.5.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3948 Release `v2022.5.0`
  CHANGELOG.md
  package.json
Labels: Ignore

#3951 Handle `sendKeyPress` events for temporary integrated consoles
  src/debugAdapter.ts
  src/features/DebugSession.ts
  src/session.ts
Labels: Issue-Bug, Area-Debugging

#3953 Fix disposal of temporary console and event handler
  src/features/DebugSession.ts
  src/session.ts
Labels: Issue-Bug, Area-Debugging

#3952 Release `v2022.5.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3957 Release `v2022.5.1`
  CHANGELOG.md
  package.json
Labels: Ignore

#3976 Add warning about intellisense to PSIC terminate dialog
  src/session.ts
Labels: Issue-Enhancement, Area-UI

#3981 Update PSIC stop message to be more concise
  src/session.ts
Labels: Issue-Bug, Area-Integrated Console, Area-UI, Ignore

#3986 Pass `EnableProfileLoading` and `InitialWorkingDirectory` as `initializationOptions`
  src/session.ts
  src/settings.ts
Labels: Issue-Bug, Area-Startup

#3987 Fix capitalization of keys in `initializationOptions`
  src/session.ts
Labels: Ignore

#3988 Release `v2022.5.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3992 Fix how we check extension mode
  src/features/ExternalApi.ts
  src/main.ts
  src/session.ts
Labels: Issue-Bug, Area-Engine

#3993 Revert modifications caused by Code's test run
  vscode-powershell.build.ps1
Labels: Issue-Bug, Area-Build & Release

#3994 Release `v2022.5.3-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3995 Release `v2022.5.4-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3996 Release `v2022.5.5-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
