Repository PowerShell/vscode-powershell, pull requests merged in 2022-08, with the labels that each got.

#4099 Fix `checkIfDirectoryExists()` so `validateCwdSetting()` works
  src/process.ts
  src/settings.ts
  src/utils.ts
Labels: Issue-Bug, Area-Workspaces

#4104 Fix edge case for workspaces defined with zero folders
  src/settings.ts
Labels: Issue-Bug, Area-Workspaces

#4105 Remove popup when extension updates
  src/main.ts
Labels: Issue-Enhancement, Area-UI

#4108 Release `v2022.8.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4120 fixes #4119
  snippets/PowerShell.json
Labels: Issue-Bug, Area-Snippets

#4121 Use `vscode.workspace.fs` and suppress startup banner for `dotnet` installs of PowerShell
  src/features/Examples.ts
  src/features/PesterTests.ts
  src/platform.ts
  src/process.ts
  src/session.ts
  src/utils.ts
  test/core/paths.test.ts
  test/core/platform.test.ts
  test/features/RunCode.test.ts
  tsconfig.json
Labels: Issue-Bug, Area-Startup

#4125 Fix debugger to start language client when necessary
  package.json
  src/features/DebugSession.ts
  src/session.ts
Labels: Issue-Enhancement, Area-UI, Area-Startup

#4126 Release `v2022.8.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4131 Update `vscode-languageclient` and refactor (a lot of TLC)
  package-lock.json
  package.json
  src/controls/checkboxQuickPick.ts
  src/features/Console.ts
  src/features/CustomViews.ts
  src/features/DebugSession.ts
  src/features/ExtensionCommands.ts
  src/features/ExternalApi.ts
  src/features/UpdatePowerShell.ts
  src/logging.ts
  src/main.ts
  src/platform.ts
  src/process.ts
  src/session.ts
  src/utils.ts
  test/core/paths.test.ts
  test/core/platform.test.ts
  test/features/CustomViews.test.ts
  test/features/RunCode.test.ts
  test/index.ts
Labels: Issue-Bug, Issue-Enhancement, Area-Startup, Area-Engine

#4133 Release `v2022.8.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4117 Add `ToggleISEMode` command with tests
  package.json
  src/features/ISECompatibility.ts
  test/features/ISECompatibility.test.ts
Labels: Issue-Enhancement, Area-ISE Compatibility

#4138 Add walkthrough telemetry command
  package.json
  src/session.ts
Labels: Ignore

#4141 Improve language client library close action message
  src/session.ts
Labels: Area-Engine

#4140 Handle edge case where user closes `cwd` picker
  src/settings.ts
Labels: Issue-Bug, Area-Startup

#4142 Release `v2022.8.3-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4147 Create a walkthrough experience for PowerShell
  media/walkthrough.md
  package.json
Labels: Issue-Enhancement, Area-Documentation

#4148 Release `v2022.8.4-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4152 Add `integratedConsole.startInBackground` to completely hide the terminal
  package.json
  src/process.ts
  src/session.ts
  src/settings.ts
Labels: Issue-Enhancement, Area-Configuration

#4153 Release `v2022.8.5-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4156 Release `v2022.8.5`
  CHANGELOG.md
  package.json
Labels: Ignore

#4139 Add setting to control the references code lens
  package.json
  src/settings.ts
Labels: Issue-Enhancement, Area-Configuration

#4161 Lock `SessionManager.start()` so only one session is started
  src/main.ts
  src/session.ts
Labels: Issue-Bug, Area-Startup
