Repository PowerShell/vscode-powershell, pull requests merged in 2022-06, with the labels that each got.

#4018 Fix outdated link to security guidelines
  README.md
Labels: Issue-Bug, Area-Documentation

#4024 Release `v2022.6.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4034 Mark unused `useX86Host` setting as deprecated
  package.json
  src/session.ts
  src/settings.ts
  test/core/paths.test.ts
Labels: Issue-Enhancement, Area-Configuration

#4046 Update tooling and READMEs for branch rename
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/codeql-analysis.yml
  .vsts-ci/azure-pipelines-ci.yml
  .vsts-ci/misc-analysis.yml
  CHANGELOG.md
  README.md
  build.ps1
  docs/azure_data_studio/README_FOR_MARKETPLACE.md
  docs/community_snippets.md
  docs/development.md
  package.json
  scripts/Install-VSCode.ps1
  src/features/GenerateBugReport.ts
  tools/ReleaseTools.psm1
Labels: Issue-Enhancement, Area-Documentation

#4058 Release `v2022.6.3-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4061 Release `v2022.6.3`
  CHANGELOG.md
  package.json
Labels: Ignore
