Repository PowerShell/vscode-powershell, pull requests merged in 2022-10, with the labels that each got.

#4195 Fix for Issue #4043
  snippets/PowerShell.json
Labels: Issue-Bug, Area-Snippets

#4198 Add 'Formatters' to extension manifest's categories
  package.json
Labels: Ignore

#4200 Release `v2022.10.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4203 Fix automatic focus to temporary debug terminal (if it exists)
  src/features/DebugSession.ts
  src/features/PesterTests.ts
  src/features/RunCode.ts
  src/main.ts
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-Debugging

#4206 Enable `strict` TypeScript mode
  src/controls/animatedStatusBar.ts
  src/controls/checkboxQuickPick.ts
  src/features/CodeActions.ts
  src/features/Console.ts
  src/features/CustomViews.ts
  src/features/DebugSession.ts
  src/features/ExpandAlias.ts
  src/features/ExtensionCommands.ts
  src/features/ExternalApi.ts
  src/features/FindModule.ts
  src/features/GenerateBugReport.ts
  src/features/GetCommands.ts
  src/features/HelpCompletion.ts
  src/features/NewFileOrProject.ts
  src/features/OpenInISE.ts
  src/features/PesterTests.ts
  src/features/RemoteFiles.ts
  src/features/ShowHelp.ts
  src/features/UpdatePowerShell.ts
  src/languageClientConsumer.ts
  src/logging.ts
  src/main.ts
  src/platform.ts
  src/process.ts
  src/session.ts
  src/settings.ts
  src/utils.ts
  test/core/platform.test.ts
  test/core/settings.test.ts
  test/features/ISECompatibility.test.ts
  test/utils.ts
  tsconfig.json
Labels: Issue-Enhancement, Area-Engine

#4209 Release `v2022.10.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#3331 Replace TSLint with ESLint
  .eslintrc.json
  .vscodeignore
  extension-dev.code-workspace
  package-lock.json
  package.json
  src/controls/checkboxQuickPick.ts
  src/features/CodeActions.ts
  src/features/Console.ts
  src/features/CustomViews.ts
  src/features/DebugSession.ts
  src/features/Examples.ts
  src/features/ExpandAlias.ts
  src/features/ExtensionCommands.ts
  src/features/ExternalApi.ts
  src/features/FindModule.ts
  src/features/GenerateBugReport.ts
  src/features/GetCommands.ts
  src/features/HelpCompletion.ts
  src/features/ISECompatibility.ts
  src/features/NewFileOrProject.ts
  src/features/OpenInISE.ts
  src/features/PesterTests.ts
  src/features/RemoteFiles.ts
  src/features/RunCode.ts
  src/features/ShowHelp.ts
  src/features/UpdatePowerShell.ts
  src/languageClientConsumer.ts
  src/logging.ts
  src/main.ts
  src/platform.ts
  src/process.ts
  src/session.ts
  src/settings.ts
  src/utils.ts
  test/core/paths.test.ts
  test/core/platform.test.ts
  test/core/settings.test.ts
  test/features/CustomViews.test.ts
  test/features/ExternalApi.test.ts
  test/features/ISECompatibility.test.ts
  test/features/RunCode.test.ts
  test/index.ts
  test/runTests.ts
  test/utils.ts
  tslint.json
  vscode-powershell.build.ps1
Labels: Issue-Enhancement, Area-Build & Release

#4214 Release `v2022.10.0`
  CHANGELOG.md
Labels: Ignore

#4220 Add assertion to build that PSES bits are built in release configuration
  .vsts-ci/templates/ci-general.yml
  vscode-powershell.build.ps1
Labels: Issue-Enhancement, Area-Build & Release

#4227 Only check a script's extension if a script file was given
  src/features/DebugSession.ts
Labels: Issue-Bug, Area-Debugging

#4228 Remove `FindModule.ts` since its long since been deprecated
  package.json
  src/features/FindModule.ts
  src/main.ts
Labels: Issue-Bug, Area-Engine

#4230 Release `v2022.10.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4233 Add cross-platform installation to walkthrough
  package.json
Labels: Issue-Bug, Area-UI
