Repository PowerShell/vscode-powershell, pull requests merged in 2022-09, with the labels that each got.

#4171 Fix incorrect docstring for `powershell.cwd`
  package.json
Labels: Issue-Bug, Area-Workspaces

#4172 Refactor the debug launch configuration resolvers
  package.json
  src/features/DebugSession.ts
  src/features/ExtensionCommands.ts
  src/features/PesterTests.ts
  src/features/RunCode.ts
  src/main.ts
  test/features/RunCode.test.ts
Labels: Issue-Bug, Area-Debugging

#4182 Update Andy's name
  README.md
  docs/azure_data_studio/README_FOR_MARKETPLACE.md
Labels: Ignore

#4183 Release `v2022.9.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4187 Re-implement indicator when running registered editor commands
  src/features/Console.ts
  src/main.ts
  src/session.ts
Labels: Issue-Enhancement, Area-UI

#4186 Only check a script's extension if a script was given
  src/features/DebugSession.ts
Labels: Issue-Bug, Area-Debugging

#4189 Release `v2022.9.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4164 Enable new PSScriptAnalyzer option `avoidSemicolonsAsLineTerminators`
  extension-dev.code-workspace
  package.json
  src/settings.ts
Labels: Issue-Enhancement, Area-Script Analysis

#4193 Handle busy notification for all PowerShell tasks
  src/features/Console.ts
  src/main.ts
  src/session.ts
Labels: Issue-Enhancement, Area-UI

#4194 Release `v2022.9.2-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
