Repository PowerShell/vscode-powershell, pull requests merged in 2023-04, with the labels that each got.

#4499 Add Git mailmap for Andy Jordan
  .mailmap
Labels: Ignore

#4500 Enable ESLint `explicit-function-return-type`
  .eslintrc.json
  src/features/CodeActions.ts
  src/features/Console.ts
  src/features/CustomViews.ts
  src/features/DebugSession.ts
  src/features/Examples.ts
  src/features/ExpandAlias.ts
  src/features/ExtensionCommands.ts
  src/features/ExternalApi.ts
  src/features/GenerateBugReport.ts
  src/features/GetCommands.ts
  src/features/HelpCompletion.ts
  src/features/ISECompatibility.ts
  src/features/NewFileOrProject.ts
  src/features/OpenInISE.ts
  src/features/PesterTests.ts
  src/features/RemoteFiles.ts
  src/features/RunCode.ts
  src/features/ShowHelp.ts
  src/features/UpdatePowerShell.ts
  src/languageClientConsumer.ts
  src/logging.ts
  src/process.ts
  src/session.ts
  src/utils.ts
  test/core/platform.test.ts
  test/features/ISECompatibility.test.ts
  test/runTests.ts
Labels: Issue-Enhancement, Area-Tech Debt

#4503 Enable VS Code unit tests in Linux CI
  .vsts-ci/templates/ci-general.yml
  vscode-powershell.build.ps1
Labels: Issue-Enhancement, Area-Build & Release

#3903 Add attachDotnetDebugger debug option
  .gitignore
  examples/.vscode/settings.json
  package-lock.json
  package.json
  src/features/DebugSession.ts
  src/process.ts
  src/session.ts
  test/core/paths.test.ts
  test/features/DebugSession.test.ts
  test/features/RunCode.test.ts
  test/features/UpdatePowerShell.test.ts
  test/index.ts
  test/mocks/BinaryModule/BinaryModule.csproj
  test/mocks/BinaryModule/BinaryModuleTest.ps1
  test/mocks/BinaryModule/TestSampleCmdletCommand.cs
  test/runTests.ts
  test/utils.ts
  tsconfig.json
Labels: Issue-Enhancement, Area-Debugging, Area-Configuration

#4511 Add Additional Debug Configuration Templates for Pester and Binary Modules
  src/features/DebugSession.ts
Labels: Feature: VS Code, Area-Debugging

#4510 Improve Extension Authoring Experience with new Build Tasks and Launch Configs
  .gitignore
  examples/.vscode/settings.json
  extension-dev.code-workspace
  package.json
  test/.vscode/settings.json
  test/TestEnvironment.code-workspace
  test/core/settings.test.ts
  test/features/DebugSession.test.ts
  test/runTests.ts
  tsconfig.json
  vscode-powershell.build.ps1
Labels: Area-Debugging

#4515 Release `v2023.4.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4516 Add new debug configurations to `package.json`
  package.json
  src/features/DebugSession.ts
  test/features/DebugSession.test.ts
Labels: Issue-Bug, Area-Debugging

#4517 Fix `attachDotnetDebugger` with custom config
  src/features/DebugSession.ts
  test/features/DebugSession.test.ts
Labels: Issue-Bug, Area-Debugging

#4518 Enable Mocha Test Explorer Integration
  .mocharc.json
  .vscode/launch.json
  .vscode/tasks.json
  extension-dev.code-workspace
  package-lock.json
  package.json
  test/features/CustomViews.test.ts
  test/features/DebugSession.test.ts
  test/features/ISECompatibility.test.ts
  test/features/UpdatePowerShell.test.ts
  test/index.ts
  test/runTests.ts
  test/runTestsInner.ts
  test/utils.ts
  tsconfig.json
Labels: Issue-Enhancement, Area-Build & Release

#4532 Handle end-of-support PowerShell with error message
  src/features/GenerateBugReport.ts
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-Tech Debt

#4541 Fix Dependabot pull requests limit
  .github/dependabot.yml
Labels: Area-Build & Release, Ignore

#4543 Update startup logic to handle session failure reasons
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-Startup

#4547 Fix flaky test
  .mocharc.json
  test/core/settings.test.ts
  test/features/CustomViews.test.ts
  test/features/DebugSession.test.ts
  test/features/ISECompatibility.test.ts
  test/features/RunCode.test.ts
  test/features/UpdatePowerShell.test.ts
Labels: Issue-Bug, Area-Test

#4548 Use named debug configurations instead of duplicating them
  src/features/DebugSession.ts
  src/features/ExtensionCommands.ts
  src/features/ISECompatibility.ts
  test/features/DebugSession.test.ts
Labels: Issue-Enhancement, Area-Tech Debt
