Repository PowerShell/vscode-powershell, pull requests merged in 2023-08, with the labels that each got.

#4696 Fix race condition with displaying PowerShell name on icon
  src/session.ts
  src/settings.ts
Labels: Issue-Bug, Area-UI

#4711 Update extension telemetry dependency
  package-lock.json
  package.json
Labels: dependencies

#4707 Move `--sourcemap` to scripts instead of `Invoke-Build`
  package.json
  vscode-powershell.build.ps1
Labels: Issue-Enhancement, Area-Build & Release
