Repository PowerShell/vscode-powershell, pull requests merged in 2023-02, with the labels that each got.

#4401 Release `v2023.2.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4416 Release `v2023.2.1-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4417 Fix up dependencies
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#4420 Delete skipped examples folder test
  test/core/paths.test.ts
Labels: Ignore

#4425 Hide last line in folded ranges for ISE Mode
  src/features/ISECompatibility.ts
Labels: Issue-Enhancement, Area-ISE Compatibility

#4431 Release `v2023.2.1`
  CHANGELOG.md
  package.json
Labels: Ignore
