Repository PowerShell/vscode-powershell, pull requests merged in 2023-01, with the labels that each got.

#4347 fix class snippet (unnecessary space between `<` and `#`)
  snippets/PowerShell.json
Labels: Issue-Bug, Area-Snippets

#4357 Fix `@vscode/vsce` dependency after its rename
  README.md
  docs/development.md
  package-lock.json
  package.json
Labels: Issue-Bug, Area-Build & Release

#4358 Release `v2023.1.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4384 Release `v2023.1.0`
  CHANGELOG.md
  package.json
Labels: Ignore
