Repository PowerShell/vscode-powershell, pull requests merged in 2024-01, with the labels that each got.

#4879 Release `v2024.1.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore

#4883 Add developer setting to disable `-ExecutionPolicy Bypass` flags
  package.json
  src/process.ts
  src/session.ts
  src/settings.ts
Labels: Issue-Enhancement, Area-Configuration, Area-Startup

#4886 Release `v2024.0.0`
  CHANGELOG.md
  package.json
Labels: Ignore

#4900 Fix `PowerShellProcess.dipose()` to fire the `onExited` event idempotently
  src/process.ts
  src/session.ts
Labels: Issue-Bug, Area-Extension Terminal

#4902 Enable LanguageClient Tracing Option
  docs/troubleshooting.md
  package.json
  src/session.ts
Labels: Issue-Enhancement, Area-Configuration

#4903 Release `v2024.3.0-preview`
  CHANGELOG.md
  package.json
Labels: Ignore
