Repository PowerShell/vscode-powershell, pull requests merged in 2024-10, with the labels that each got.

#5034 Fix "Suppress a PSScriptAnalyzer rule on a parameter" snippet
  snippets/PowerShell.json
Labels: Area-Snippets

#4423 Add "`foreach` with `Write-Progress`" snippet
  snippets/PowerShell.json
Labels: Area-Snippets

#5059 Add setting to use either `.` or `&` when launching script
  package.json
  src/features/DebugSession.ts
  src/settings.ts
Labels: Area-Debugging

#5061 Bump packages
  docs/development.md
  package-lock.json
  package.json
Labels: Area-Build & Release

#5062 Set expected shell integration environment variables
  src/process.ts
  src/session.ts
Labels: Area-Extension Terminal

#5064 Enable ability to trace DAP messages at client side
  package.json
  src/features/DebugSession.ts
  src/session.ts
  test/features/DebugSession.test.ts
Labels: Issue-Enhancement, Area-Debugging

#5071 Refactor: Replace package.json requires with extension context info
  src/extension.ts
Labels: Area-Startup

#5076 Fix: Change DAP send/receive glyph to keep things aligned in the logs
  src/features/DebugSession.ts
Labels: Issue-Bug, Area-Logging, Bug: Pre-release
