Repository PowerShell/vscode-powershell, pull requests merged in 2024-11, with the labels that each got.

#5090 Update the end-of-support message for PowerShell <7.4
  src/session.ts
Labels: Issue-Enhancement

#5065 Implement LogOutputWindow for Logging
  docs/troubleshooting.md
  package.json
  src/extension.ts
  src/features/DebugSession.ts
  src/features/ExternalApi.ts
  src/features/UpdatePowerShell.ts
  src/logging.ts
  src/process.ts
  src/session.ts
  src/settings.ts
  test/core/paths.test.ts
  test/utils.ts
Labels: Issue-Enhancement

#5093 Clarify and simplify platform support statements
  README.md
Labels: Issue-Enhancement

#5099 Improve warning when additional PowerShell isn't found
  src/platform.ts
  test/core/platform.test.ts
Labels: Issue-Bug

#5100 Fix additional PowerShell warning (take two)
  src/platform.ts
  test/core/platform.test.ts
Labels: Issue-Bug

#5094 Dev: Optimize Launch Configs and Enable Hot Reload
  .vscode/launch.json
  .vscode/tasks.json
  docs/development.md
  extension-dev.code-workspace
  package.json
  pwsh-extension-dev.code-workspace
  src/extension.ts
  src/process.ts
  src/session.ts
Labels: Issue-Enhancement

#5105 Add Prettier extension to recommendations
  pwsh-extension-dev.code-workspace
Labels: Ignore
