Repository PowerShell/vscode-powershell, pull requests merged in 2025-06, with the labels that each got.

#5208 Feature: Add sessionName debug setting to allow different PS for temp console
  package.json
  src/features/DebugSession.ts
  src/session.ts
Labels: Issue-Enhancement, Area-Debugging

#5220 Shell integration script moved back
  src/utils.ts
Labels: Area-Extension Terminal

#5222 v2025.3.1-preview: PowerShell installed via `brew` now found!
  CHANGELOG.md
  package.json
Labels: Ignore
